M48
; DRILL file {KiCad 9.0.1} date 2025-05-13T00:09:30-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-05-13T00:09:30-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0390
%
G90
G05
T1
X1.8447Y-3.0516
X1.8447Y-3.2791
T2
X2.3232Y-3.0165
X2.3232Y-3.0965
X2.5232Y-3.0565
M30
